### PR TITLE
Shim `process`

### PR DESCRIPTION
**Pull request by chenglou**
cc @marijnh

### CODE REVIEW

**Comment by marijnh** [comment]
I don't think this belongs in moduleserve. Should be easy enough to load your own file that does this.

**Comment by chenglou** [comment]
Yeah you're right. Thanks!
Should I submit a PR to mention this in the README? Is it worth it?

**Comment by marijnh** [comment]
Why would anyone expect `process` to be shimmed by a module loader?

**Comment by chenglou** [comment]
Sorry, I meant whether you're open to document a recommended way, e.g. adding `<script> window.process = ... </script>`, to circumvent many frameworks checking `process`.

**Comment by marijnh** [comment]
Moduleserve isn't intended to be a solution for running node-targeting code in the browser. You might be able to use it as part of a solution for that, but I don't see it as trying to do that out of the box, so shimming node features doesn't seem relevant in our readme.

**Pull request closed without merging**
